### PR TITLE
new config param: 'sync_times' true/false. if true, sync timestamps of files and templates

### PR DESCRIPTION
**Pull request by dl4ner**
we want to have also file timestamps to be synced with synctool

pro: 
beeing able to touch a file at a central place

con:
some more stat() requests

to make the change non-invasieve there is a config param 
    sync_times  (False/True) 
which defaults to False (current behaviour).

* sync_times will only touch timestamps of files
* sync_times will also copy timestamp of template source to generated templates - else this would give a timestamp error at each run for each template.

I hope I did not oversee some point.

### CODE REVIEW

**Comment by walterdejong** [comment]
Hi,

Thanks for this patch! It is very good, but some thoughts:
* synctool has a `SyncStat` object that caches inode metadata so that it doesn't have to call `stat()` all the time. The `SyncStat` object doesn't cache the times, because it didn't need to -- but now it should
* `shutil.copy2()` will copy times, so you could use this rather than calling `copy()` and `copystat()`. Under the hood, `shutil` does the same thing, however
* setting the times of a directory is also possible in Unix. Probably not for a symbolic link
* `int(mtime)` doesn't make any sense. It should already be an integer value. If it is giving problems, there is maybe some other bug going on

I'm planning to accept the patch and address these points, when I get some time :)
Anyway, many thanks && greets!

**Comment by dl4ner** [comment]
Hi Walter,

--Walter de Jong <notifications@github.com> Dienstag, 15. Dezember 2015 01:40 -0800:

> Thanks for this patch! It is very good, but some thoughts:

:)

> * synctool has a `SyncStat` object that caches inode metadata so
> that it doesn't have to call `stat()` all the time. The `SyncStat`
> object doesn't cache the times, because it didn't need to -- but now it should

well, - this has been my second patch in a foreign language - it has mostly been
copy&paste and some hints from good old aunt google :D

> * `shutil.copy2()` will copy times, so you could use this rather
> than calling `copy()` and `copystat()`. Under the hood, `shutil`
> does the same thing, however

on this way ist is clearly splittable if one wants to have the old or the
new behaviour.

for some installations it could be interesting WHEN a file really has been
changed last on that particular node - on other installations it is more
important to have a central point.

> * setting the times of a directory is also possible in Unix.

we discussed internally and came to the thinking that it is necessary for _us_
to have the file stamps synced, and indeed it might be useful to have the
nodes directory timestamp - we have also directories that contain a mix of
globally (synctool-managed) files and local files - so that would differ
for each synctool run - so I left the directories out on purpuse.

> Probably not for a symbolic link

yepp. so it boils down to files and directories.

> * `int(mtime)` doesn't make any sense. It should already be an integer value.
> If it is giving problems, there is maybe some other bug going on

I had it wihtout int() before. it did work, but on one node (the master node)
it did not work - it showed differences - even after a stdout(...) of both
mtimes did show the same number.
a int() fixed the symptom - but for sure not the cause.
all other 200+ nodes were running fine.

> I'm planning to accept the patch and address these points, when I get some time :)
> Anyway, many thanks && greets!

thanks. and I don't have problems with anybody having more python experience to
review my code and give hints or change it :D

Cheers

		Werner
--
Dipl.-Ing. Univ. Werner Maier
http://www.maiers.de/

**Comment by walterdejong** [comment]
Hi,

> it could be interesting WHEN a file really has been changed

So true. UNIX already sets the mtime, but that's the time when synctool updated the file. Your patch sets the mtime of the file as it is in the repository -- which is the time when the sysadmin changed the file.
It makes a lot of sense and maybe this should be default behaviour.

The thing with `int(mtime)` happens because the `stat().st_mtime` field is actually a float value in Python. (I did not expect this ... the docs say this changed in Python 2.5). Modern OSes and filesystems may be able to provide times with sub second precision.

**Comment by walterdejong** [comment]
This code has a hidden bug (that is never triggered):
```
************* Module synctool.object
src/synctool/object.py:198: E1101 Instance of 'VNode' has no 'src_path' member
src/synctool/object.py:199: E1101 Instance of 'VNode' has no 'src_path' member
```
which is in `VNode.copy_stat()`.

In practice, `copy_stat()` only gets called in `VNodeFile` objects, which does have the `src_path` member.
I will change this.

**Pull request merged**
